#%RAML 0.8 ResourceType
description: Collection of <<resourcePathName>>
get:
  description: Get a list of <<resourcePathName>>.
  responses:
    200:
      body:
        application/json:
          example: |
            <<example_collection>>
